# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [11]:
# No code solution (reading)
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.9.0+cpu
False


### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch;
tensor2 = torch.rand(7, 7)
print(tensor2)
print(tensor2.shape)

# Create random tensor

tensor([[0.3016, 0.7855, 0.8214, 0.4051, 0.5126, 0.5045, 0.9737],
        [0.2015, 0.1407, 0.7868, 0.4294, 0.8284, 0.2345, 0.0509],
        [0.0725, 0.5407, 0.1604, 0.8021, 0.0669, 0.3177, 0.7292],
        [0.8835, 0.1730, 0.2035, 0.5136, 0.3664, 0.3755, 0.6796],
        [0.3921, 0.1446, 0.1326, 0.4160, 0.7886, 0.5120, 0.3558],
        [0.3505, 0.4257, 0.0743, 0.3332, 0.4446, 0.2983, 0.7274],
        [0.5130, 0.3459, 0.3764, 0.8879, 0.2053, 0.6718, 0.9775]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
tensor3 = torch.rand(1, 7)
# Perform matrix multiplication 
result3 = torch.matmul(tensor2, tensor3.T)
print(result3)
print(result3.shape)

tensor([[2.6527],
        [1.5143],
        [1.6437],
        [2.0955],
        [1.3882],
        [1.4962],
        [2.5998]])
torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor4a = torch.rand(7, 7)
tensor4b = torch.rand(1, 7)

# Matrix multiply tensors
result4 = torch.matmul(tensor4a, tensor4b.T)
print(result4)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(1234)
# Check for access to GPU
tensor6a = torch.rand(2, 3).to(device)
tensor6b = torch.rand(2, 3).to(device)
# Create two random tensors on GPU
print(tensor6a)
print(tensor6b)
print(tensor6a.device, tensor6b.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])
cpu cpu



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
result7 = torch.matmul(tensor6a, tensor6b.T)
print(result7)
print(result7.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
max_val = result7.max()
min_val = result7.min()
# Find min
print("Max:", max_val)
print("Min:", min_val)

Max: tensor(0.5617)
Min: tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
# Find arg max
max_idx = torch.argmax(result7)
min_idx = torch.argmin(result7)

# Find arg min
print("Index of max:", max_idx.item())
print("Index of min:", min_idx.item())

Index of max: 3
Index of min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
# Set seed
torch.manual_seed(7)
# Create random tensor
tensor_10 = torch.rand(1, 1, 1, 10)
print("Original tensor shape:", tensor_10.shape)
# Remove single dimensions
tensor_squeezed = tensor_10.squeeze()

# Print out tensors and their shapes
print("After squeeze:", tensor_squeezed.shape)
print(tensor_squeezed)

Original tensor shape: torch.Size([1, 1, 1, 10])
After squeeze: torch.Size([10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
